#!/bin/bash

# Xcode Cloud runs this hook on a fresh runner. Recreate JavaScript and CocoaPods
# dependencies on that runner instead of trying to repair Pods generated on a
# developer machine. This keeps native paths deterministic and avoids pnpm
# store paths leaking into the Xcode project.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Custom Xcode Cloud hooks can start with a smaller PATH than an interactive
# shell. Add the standard Apple Silicon + Intel Homebrew locations before
# invoking Node/npm/pod so preinstalled tools can actually be discovered.
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$PATH"

find_brew() {
  if command -v brew >/dev/null 2>&1; then
    command -v brew
    return 0
  fi
  for candidate in /opt/homebrew/bin/brew /usr/local/bin/brew; do
    if [[ -x "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

ensure_node() {
  if command -v node >/dev/null 2>&1; then
    return 0
  fi

  local brew_bin
  brew_bin="$(find_brew || true)"
  if [[ -z "$brew_bin" ]]; then
    echo "[Velora CI] Node is not available and Homebrew could not be found." >&2
    echo "[Velora CI] PATH=$PATH" >&2
    exit 1
  fi

  echo "[Velora CI] Node not found in PATH; installing Node 22 with Homebrew"
  "$brew_bin" install node@22

  local node_prefix
  node_prefix="$("$brew_bin" --prefix node@22)"
  export PATH="$node_prefix/bin:$PATH"

  if ! command -v node >/dev/null 2>&1; then
    echo "[Velora CI] Node installation completed but node is still unavailable." >&2
    echo "[Velora CI] PATH=$PATH" >&2
    exit 1
  fi
}

echo "[Velora CI] Preparing Xcode Cloud runner"
ensure_node
echo "[Velora CI] Node: $(node --version) ($(command -v node))"
echo "[Velora CI] npm: $(npm --version) ($(command -v npm))"

# Restore Firebase configuration without committing the production plist.
# Expo reads the root copy from app.json, while the checked-in Xcode project
# references ios/veloraDev/GoogleService-Info.plist as a build resource.
FIREBASE_ROOT_PLIST="$REPO_ROOT/GoogleService-Info.plist"
FIREBASE_IOS_PLIST="$REPO_ROOT/ios/veloraDev/GoogleService-Info.plist"

if [[ -n "${GOOGLE_SERVICE_INFO_PLIST_BASE64:-}" ]]; then
  echo "[Velora CI] Restoring GoogleService-Info.plist"
  mkdir -p "$(dirname "$FIREBASE_IOS_PLIST")"
  if base64 --decode >/dev/null 2>&1 <<<""; then
    printf '%s' "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 --decode > "$FIREBASE_ROOT_PLIST"
  else
    printf '%s' "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 -D > "$FIREBASE_ROOT_PLIST"
  fi
  cp "$FIREBASE_ROOT_PLIST" "$FIREBASE_IOS_PLIST"
fi

if [[ ! -s "$FIREBASE_ROOT_PLIST" ]]; then
  echo "[Velora CI] Missing root GoogleService-Info.plist. Add GOOGLE_SERVICE_INFO_PLIST_BASE64 to the Xcode Cloud workflow." >&2
  exit 1
fi

if [[ ! -s "$FIREBASE_IOS_PLIST" ]]; then
  echo "[Velora CI] Missing Xcode Firebase plist: $FIREBASE_IOS_PLIST" >&2
  exit 1
fi

# Validate the secret decoded into a real plist before spending time on pods.
/usr/libexec/PlistBuddy -c 'Print :GOOGLE_APP_ID' "$FIREBASE_IOS_PLIST" >/dev/null

echo "[Velora CI] Firebase plist ready for Expo and Xcode"

# package.json pins pnpm@9.15.0. Corepack is not guaranteed to ship with every
# Node release, so use it when present and fall back to npx otherwise.
if command -v corepack >/dev/null 2>&1; then
  PNPM=(corepack pnpm)
else
  echo "[Velora CI] Corepack is unavailable; using pnpm 9.15.0 through npx"
  PNPM=(npx --yes pnpm@9.15.0)
fi

echo "[Velora CI] pnpm: $("${PNPM[@]}" --version)"
HUSKY=0 CI=true "${PNPM[@]}" install --frozen-lockfile

# CocoaPods is preinstalled on Xcode Cloud. Keep a Homebrew fallback for an
# image where it is unexpectedly absent.
if ! command -v pod >/dev/null 2>&1; then
  brew_bin="$(find_brew || true)"
  if [[ -z "$brew_bin" ]]; then
    echo "[Velora CI] CocoaPods is unavailable and Homebrew could not be found." >&2
    exit 1
  fi
  echo "[Velora CI] CocoaPods not found; installing it with Homebrew"
  "$brew_bin" install cocoapods
  export PATH="$("$brew_bin" --prefix)/bin:$PATH"
fi

echo "[Velora CI] CocoaPods: $(pod --version) ($(command -v pod))"

# Remove the partially committed/generated Pods tree. pod install then creates
# Pods and the workspace using node_modules from this exact Xcode Cloud runner.
rm -rf "$REPO_ROOT/ios/Pods" "$REPO_ROOT/ios/veloraDev.xcworkspace"
(
  cd "$REPO_ROOT/ios"
  pod install
)

# React Native build phases need the runner's Node path, not a Homebrew path
# captured on a developer Mac.
cat > "$REPO_ROOT/ios/.xcode.env" <<EOF
# Generated by ci_scripts/ci_post_clone.sh for Xcode Cloud.
export NODE_BINARY="$(command -v node)"
EOF

# TestFlight/App Store archives use the production APNs environment. Local
# Debug builds keep the checked-in development entitlement unchanged.
/usr/libexec/PlistBuddy -c 'Set :aps-environment production' \
  "$REPO_ROOT/ios/veloraDev/veloraDev.entitlements"

if [[ ! -d "$REPO_ROOT/ios/veloraDev.xcworkspace" ]]; then
  echo "[Velora CI] CocoaPods did not generate ios/veloraDev.xcworkspace" >&2
  exit 1
fi

if [[ ! -f "$REPO_ROOT/ios/Pods/Manifest.lock" ]]; then
  echo "[Velora CI] CocoaPods did not generate Pods/Manifest.lock" >&2
  exit 1
fi

echo "[Velora CI] Dependencies are ready for archive"
