#!/bin/bash

# Xcode Cloud runs this script after cloning the repository and before it
# resolves the workspace configured in the workflow. The native iOS project is
# generated by Expo, so it must exist before Xcode Cloud starts xcodebuild.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "[Velora CI] Installing JavaScript dependencies"

if command -v pnpm >/dev/null 2>&1; then
  PNPM=(pnpm)
else
  # Xcode Cloud images do not guarantee pnpm is installed. npm exec keeps the
  # fallback self-contained and uses the version compatible with this lockfile.
  PNPM=(npm exec --yes --package=pnpm@9.15.0 -- pnpm)
fi

"${PNPM[@]}" install --frozen-lockfile

if [[ -n "${GOOGLE_SERVICE_INFO_PLIST_BASE64:-}" ]]; then
  echo "[Velora CI] Restoring GoogleService-Info.plist from CI secret"
  if base64 --decode >/dev/null 2>&1 <<<""; then
    printf '%s' "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 --decode > "$REPO_ROOT/GoogleService-Info.plist"
  else
    printf '%s' "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 -D > "$REPO_ROOT/GoogleService-Info.plist"
  fi
fi

if [[ ! -f "$REPO_ROOT/GoogleService-Info.plist" ]]; then
  echo "[Velora CI] Missing GoogleService-Info.plist. Add GOOGLE_SERVICE_INFO_PLIST_BASE64 to Xcode Cloud environment variables." >&2
  exit 1
fi

echo "[Velora CI] Generating iOS workspace with Expo prebuild"
npx expo prebuild --platform ios --no-install

if ! command -v pod >/dev/null 2>&1; then
  echo "[Velora CI] CocoaPods is required on the Xcode Cloud runner" >&2
  exit 1
fi

echo "[Velora CI] Installing CocoaPods dependencies"
(cd "$REPO_ROOT/ios" && pod install)

# Expo writes a machine-specific NODE_BINARY value. Xcode Cloud needs a path
# resolved on the current runner instead of a developer's Homebrew path.
cat > "$REPO_ROOT/ios/.xcode.env" <<'EOF'
# Generated by ci_scripts/ci_post_clone.sh for Xcode Cloud.
export NODE_BINARY="$(command -v node)"
EOF

echo "[Velora CI] Ready: ios/veloraDev.xcworkspace"
echo "[Velora CI] TestFlight push-trigger verification"
