#!/bin/bash

# Xcode Cloud runs this hook on a fresh runner. Recreate JavaScript and CocoaPods
# dependencies on that runner instead of trying to repair Pods generated on a
# developer machine. This keeps native paths deterministic and avoids pnpm
# store paths leaking into the Xcode project.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "[Velora CI] Preparing Xcode Cloud runner"
echo "[Velora CI] Node: $(node --version)"

# Restore Firebase configuration without committing the production plist.
if [[ -n "${GOOGLE_SERVICE_INFO_PLIST_BASE64:-}" ]]; then
  echo "[Velora CI] Restoring GoogleService-Info.plist"
  if base64 --decode >/dev/null 2>&1 <<<""; then
    printf '%s' "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 --decode > "$REPO_ROOT/GoogleService-Info.plist"
  else
    printf '%s' "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 -D > "$REPO_ROOT/GoogleService-Info.plist"
  fi
fi

if [[ ! -f "$REPO_ROOT/GoogleService-Info.plist" ]]; then
  echo "[Velora CI] Missing GoogleService-Info.plist. Add GOOGLE_SERVICE_INFO_PLIST_BASE64 to the Xcode Cloud workflow." >&2
  exit 1
fi

# package.json pins pnpm@9.15.0. Prefer Corepack so CI uses that exact package
# manager without mutating the system Node installation.
if command -v corepack >/dev/null 2>&1; then
  PNPM=(corepack pnpm)
else
  echo "[Velora CI] Corepack is unavailable; using pnpm 9.15.0 through npx"
  PNPM=(npx --yes pnpm@9.15.0)
fi

echo "[Velora CI] pnpm: $("${PNPM[@]}" --version)"
HUSKY=0 CI=true "${PNPM[@]}" install --frozen-lockfile

# Xcode Cloud images normally include CocoaPods. Keep a fallback for runner
# images where the executable is not preinstalled.
if ! command -v pod >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    echo "[Velora CI] Installing CocoaPods with Homebrew"
    brew install cocoapods
  else
    echo "[Velora CI] Installing CocoaPods as a user gem"
    gem install --user-install cocoapods --no-document
    export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
  fi
fi

echo "[Velora CI] CocoaPods: $(pod --version)"

# Remove the partially committed/generated Pods tree. pod install then creates
# Pods and the workspace using node_modules from this exact Xcode Cloud runner.
rm -rf "$REPO_ROOT/ios/Pods" "$REPO_ROOT/ios/veloraDev.xcworkspace"
(
  cd "$REPO_ROOT/ios"
  pod install
)

# React Native build phases need the runner's Node path, not a Homebrew path
# captured on a developer Mac.
cat > "$REPO_ROOT/ios/.xcode.env" <<EOF
# Generated by ci_scripts/ci_post_clone.sh for Xcode Cloud.
export NODE_BINARY="$(command -v node)"
EOF

# TestFlight/App Store archives use the production APNs environment. Local
# Debug builds keep the checked-in development entitlement unchanged.
/usr/libexec/PlistBuddy -c 'Set :aps-environment production' \
  "$REPO_ROOT/ios/veloraDev/veloraDev.entitlements"

if [[ ! -d "$REPO_ROOT/ios/veloraDev.xcworkspace" ]]; then
  echo "[Velora CI] CocoaPods did not generate ios/veloraDev.xcworkspace" >&2
  exit 1
fi

if [[ ! -f "$REPO_ROOT/ios/Pods/Manifest.lock" ]]; then
  echo "[Velora CI] CocoaPods did not generate Pods/Manifest.lock" >&2
  exit 1
fi

echo "[Velora CI] Dependencies are ready for archive"
