export const LOCAL_MESSAGE_HARD_LIMIT = 1000
export const INITIAL_LOCAL_MESSAGE_DISPLAY_LIMIT = 50
export const LOCAL_MESSAGE_DISPLAY_STEP = 50
export const LOCAL_MESSAGE_PROTECTED_STATUSES = ['PENDING', 'FAILED'] as const
